version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "PKHeX.Core"
  - package-ecosystem: "nuget"
    directory: "/WC3Plugin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "PKHeX.Core"
